# Generated by Django 3.1.5 on 2021-01-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('open_price', models.FloatField()),
                ('open_date', models.CharField(max_length=25)),
                ('close_price', models.FloatField()),
                ('close_date', models.CharField(max_length=25)),
                ('stoploss', models.FloatField()),
                ('takeprofit', models.FloatField()),
                ('profit', models.FloatField()),
                ('symbol', models.CharField(max_length=20)),
                ('ticket', models.PositiveIntegerField()),
                ('type_operation', models.CharField(max_length=11)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
